### ISSUE TITLE
ryser_tensor does not pass runtests

### ISSUE THREAD

**Issue by AntoineRestivo** [benoitseron/Permanents.jl#10]
https://github.com/benoitseron/Permanents.jl/blob/8a776dfcb63710a582169e484411ea9465a03134/test/runtests.jl#L87

Any idea where the error could come from in the algorithm? I would like to use this as a basis to add grey code

**Comment by benoitseron** [comment]
It worked on my machine, what error do you have?

**Comment by AntoineRestivo** [comment]
> Test threw exception
  Expression: ryser_tensor(W) ≈ multi_dim_ryser(U, S)
  UndefVarError: U not defined
  Stacktrace:
    [1] ryser_tensor(W::Array{ComplexF64, 3})
      @ Permanents ~/Desktop/Permanents.jl-main/src/Permanents.jl:49

Which is 
`n = size(U)[1]`
Perhaps you meant
'n=size(W)[1]'? 

I did not try to understand the Algorithm yet

**Comment by benoitseron** [comment]
The test is this:

`n = 7
	U = rand_haar(n)
	S = rand_gram_matrix(n)

	W = Array{eltype(S)}(undef, (n,n,n))

	for ss in 1:n
	    for rr in 1:n
	        for j in 1:n
	            W[ss,rr,j] = U[ss, j] * conj(U[rr, j]) * S[rr, ss]
	        end
	    end
	end

	@test ryser_tensor(W) ≈  multi_dim_ryser(U, S)`

**Comment by AntoineRestivo** [comment]
That's not my point. 
Here 
https://github.com/benoitseron/Permanents.jl/blob/8a776dfcb63710a582169e484411ea9465a03134/src/Permanents.jl#L88
I don't know why its U but ok it works well with W instead
