### ISSUE TITLE
ryser does not support non square matrix

### ISSUE THREAD

**Issue by AntoineRestivo** [benoitseron/Permanents.jl#4]
One temporary solution could be to add the good old fast_perm in case the input matrix is not squared

**Comment by benoitseron** [comment]
I don't think the permanent is defined for non square matrices, where did you need that? 

There is of course an equivalent in terms of just sums and products when computing amplitudes but I don't think it has a special name

**Comment by AntoineRestivo** [comment]
No no I am just saying that the function does not work anymore with the matrix I input in noisy_distribution (line 50) < distributions < BosonSampling.jl, while for an obscure reason naive works fine.

**Comment by benoitseron** [comment]
you need to change permanent ryser to "ryser" no?

**Comment by AntoineRestivo** [comment]
No I had already changed it but the problem is fixed!
