### ISSUE TITLE
Combinatorics dependancy

### ISSUE THREAD

**Issue by benoitseron** [benoitseron/Permanents.jl#7]
@AntoineRestivo do you also have the same problem with Combinatorics? I didn't manage to fix it

`[ Info: Precompiling Permanents [e0809bc7-674c-4283-bd35-3a6d484c6d12]
┌ Warning: Package Permanents does not have Combinatorics in its dependencies:
│ - If you have Permanents checked out for development and have
│   added Combinatorics as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Permanents
└ Loading Combinatorics into Permanents from project dependency, future warnings for Permanents are suppressed.`

**Comment by AntoineRestivo** [comment]
After which command do you get this? Here I just did Pkg.add("Permanents") and everything works fine on my side

**Comment by benoitseron** [comment]
Indeed this works, by adding the package from the online repository. It used my local version of the package before, so it may bug in the future in the same way. Now it works at least. (It's strange because I pulled the package so they should be the same.)
